version: '3.8'

services:
  validation-service:
    container_name: python-image-file-validation-service
    build:
      context: ../image_validation
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      FILE_STORAGE_URL: "http://file-storage:5000"
      DATABASE_URL: "postgresql://admin@db:5432/postgres"